export const STRINGS = {
  "tabs.general": "General",
  "tabs.notes": "Notes",
  "tabs.bases": "Bases",
  "tabs.sync": "Sync",
  "tabs.daily": "Daily Notes",
  "bases.heading": "Obsidian Bases",
  "bases.help": "Generate optional database-style views from your Trakt note properties.",
  "bases.folder.name": "Bases folder",
  "bases.folder.desc": "Folder where generated .base files will be saved.",
  "bases.actions.heading": "Create Bases",
  "bases.library.name": "All-in-one Library Base",
  "bases.library.desc": "One combined library containing movies and TV shows.",
  "bases.movies.name": "Movies Base",
  "bases.movies.desc": "Movie notes with their key metadata.",
  "bases.shows.name": "Shows Base",
  "bases.shows.desc": "TV show notes with their key metadata.",
  "bases.watchlist.name": "Watchlist Base",
  "bases.watchlist.desc": "Items currently on your watchlist.",
  "bases.watched.name": "Watched Base",
  "bases.watched.desc": "Items marked as watched.",
  "bases.ratings.name": "Ratings Base",
  "bases.ratings.desc": "Items with a personal rating.",
  "bases.all.name": "All Bases",
  "bases.all.desc": "Create every Base preset.",
  "bases.createMovies": "Create Movies Base",
  "bases.createShows": "Create Shows Base",
  "bases.createWatchlist": "Create Watchlist Base",
  "bases.createWatched": "Create Watched Base",
  "bases.createRatings": "Create Ratings Base",
  "bases.createLibrary": "Create Library Base",
  "bases.createAll": "Create All Bases",
  "bases.fields.heading": "Choose fields shown in each Base",
  "bases.fields.desc": "Poster and title are always shown. Choose any additional properties.",
  "bases.fields.selectedCount": "{count} selected",
  "bases.fields.recommended": "Recommended",
  "bases.fields.all": "Select all",
  "bases.fields.none": "Clear",
  "bases.group.core": "Core metadata",
  "bases.group.ratings": "Ratings",
  "bases.group.activity": "Viewing activity",
  "bases.group.progress": "TV progress",
  "bases.group.release": "Release details",
  "bases.group.localization": "Metadata",
  "bases.group.links": "IDs and links",
  "bases.group.sync": "Sync metadata",
  "bases.view.posters": "Posters",
  "bases.view.details": "Details",
  "bases.value.watched": "✓ Watched",
  "bases.value.watchlist": "＋ Watchlist",
  "bases.field.title": "Title",
  "bases.field.poster": "Poster",
  "bases.field.posterUrl": "Poster URL",
  "bases.field.type": "Media type",
  "bases.field.year": "Year",
  "bases.field.genres": "Genres",
  "bases.field.overview": "Overview",
  "bases.field.runtime": "Runtime",
  "bases.field.certification": "Certification",
  "bases.field.country": "Country",
  "bases.field.language": "Language",
  "bases.field.tags": "Tags",
  "bases.field.tagNotes": "Tag notes",
  "bases.field.communityRating": "Trakt rating",
  "bases.field.votes": "Trakt votes",
  "bases.field.personalRating": "My rating",
  "bases.field.libraryStatus": "Watched / watchlist status",
  "bases.field.watched": "Watched",
  "bases.field.watchlist": "Watchlist",
  "bases.field.favorite": "Favorite",
  "bases.field.plays": "Play count",
  "bases.field.lastWatched": "Last watched",
  "bases.field.watchlistAdded": "Added to watchlist",
  "bases.field.favoritedAt": "Favorited at",
  "bases.field.ratedAt": "Rated at",
  "bases.field.episodeProgress": "Episode progress",
  "bases.field.episodesWatched": "Episodes watched",
  "bases.field.airedEpisodes": "Aired episodes",
  "bases.field.showStatus": "Show status",
  "bases.field.network": "Network",
  "bases.field.firstAired": "First aired",
  "bases.field.released": "Release date",
  "bases.field.tagline": "Tagline",
  "bases.field.originalTitle": "Original title",
  "bases.field.originalOverview": "Original overview",
  "bases.field.originalTagline": "Original tagline",
  "bases.field.originalGenres": "Original genres",
  "bases.field.metadataLanguage": "Metadata language",
  "bases.field.traktId": "Trakt ID",
  "bases.field.slug": "Trakt slug",
  "bases.field.imdbId": "IMDB ID",
  "bases.field.tmdbId": "TMDB ID",
  "bases.field.tvdbId": "TVDB ID",
  "bases.field.traktUrl": "Trakt URL",
  "bases.field.imdbUrl": "IMDB URL",
  "bases.field.syncedAt": "Last note change",
  "bases.field.communityStatsSyncedAt": "Community stats updated",
  "bases.confirmOverwrite.title": "Overwrite existing Base?",
  "bases.confirmOverwrite.body": "{filename} already exists at {path}.\nOverwriting it will replace any manual edits.",
  "bases.confirmOverwrite.confirm": "Overwrite",
  "bases.notice.created": "Trakt Vault Sync: created {filename} at {path}.",
  "bases.notice.updated": "Trakt Vault Sync: updated {filename} at {path}.",
  "bases.notice.skipped": "Trakt Vault Sync: kept the existing {filename}.",
  "bases.notice.failed": "Trakt Vault Sync: failed to create {filename} — {msg}",
  "bases.error.folderPathIsFile": "A file already exists where the folder should be: {path}",
  "bases.error.targetIsNotFile": "The target path is not a writable file: {path}",
  "daily.heading": "Daily notes integration",
  "daily.enabled.name": "Enable Daily Notes integration",
  "daily.enabled.desc": "Insert Trakt events into existing Daily Notes.",
  "daily.folder.name": "Daily Notes folder",
  "daily.folder.desc": "Must be an existing folder.",
  "daily.format.name": "Filename format",
  "daily.format.desc": "Moment.js format string matching your Daily Notes filenames.",
  "daily.markerStart.name": "Start marker",
  "daily.markerEnd.name": "End marker",
  "daily.marker.desc": "Markers bound the content managed by this plugin.",
  "daily.warning": "Keep manual notes outside the managed markers.",
  "daily.preview.name": "Entry format preview",
  "daily.preview.desc": "Entries use the format: time — action item.",
  "daily.sources.heading": "Source events",
  "daily.sources.desc": "Disabled sync sources are omitted.",
  "daily.sources.watched": "Watched",
  "daily.sources.watchlist": "Added to watchlist",
  "daily.sources.favorites": "Favorited",
  "daily.sources.ratings": "Rated",
  "daily.autoSync.heading": "Daily Notes-only auto-sync",
  "daily.autoSync.name": "Auto-update Daily Notes",
  "daily.autoSync.desc": "Refresh Daily Notes without rewriting media notes.",
  "daily.autoSync.interval.name": "Daily Notes auto-sync interval (minutes)",
  "daily.autoSync.interval.desc": "Minimum 5, maximum 360.",
  "daily.syncMode.heading": "Sync mode",
  "daily.syncMode.name": "Today's sync mode",
  "daily.syncMode.desc": "Default replaces managed content; incremental preserves edits.",
  "daily.syncMode.default": "Default",
  "daily.syncMode.incremental": "Incremental",
  "daily.syncMode.table.col.scenario": "Scenario",
  "daily.syncMode.table.col.default": "Default",
  "daily.syncMode.table.col.incremental": "Incremental",
  "daily.syncMode.table.row.append.scenario": "Append text",
  "daily.syncMode.table.row.append.default": "Deleted",
  "daily.syncMode.table.row.append.incremental": "Preserved",
  "daily.syncMode.table.row.insert.scenario": "Insert a custom line",
  "daily.syncMode.table.row.insert.default": "Deleted",
  "daily.syncMode.table.row.insert.incremental": "Preserved",
  "daily.syncMode.table.row.delete.scenario": "Delete a rendered line",
  "daily.syncMode.table.row.delete.default": "Restored",
  "daily.syncMode.table.row.delete.incremental": "Re-added",
  "daily.syncMode.table.row.edit.scenario": "Edit a rendered line",
  "daily.syncMode.table.row.edit.default": "Deleted",
  "daily.syncMode.table.row.edit.incremental": "Both lines coexist",
  "daily.syncMode.table.row.lang.scenario": "Change title metadata",
  "daily.syncMode.table.row.lang.default": "Re-renders",
  "daily.syncMode.table.row.lang.incremental": "Both versions coexist",
  "daily.syncMode.table.row.rating.scenario": "Change rating",
  "daily.syncMode.table.row.rating.default": "Rating updates",
  "daily.syncMode.table.row.rating.incremental": "Both ratings coexist",
  "daily.syncMode.table.row.removed.scenario": "Delete event on Trakt",
  "daily.syncMode.table.row.removed.default": "Line disappears",
  "daily.syncMode.table.row.removed.incremental": "Old line stays",
  "daily.backfill.heading": "Manual backfill",
  "daily.backfill.button.desc": "Fill existing Daily Notes in a date range.",
  "daily.backfill.button": "Backfill…",
  "daily.backfill.modal.title": "Backfill Daily Notes",
  "daily.backfill.modal.presetLabel": "Quick select",
  "daily.backfill.modal.preset.last7": "Last 7 days",
  "daily.backfill.modal.preset.last30": "Last 30 days",
  "daily.backfill.modal.preset.thisMonth": "This month",
  "daily.backfill.modal.preset.lastMonth": "Last month",
  "daily.backfill.modal.startDate": "Start date",
  "daily.backfill.modal.endDate": "End date",
  "daily.backfill.modal.rangeDays": "Range: {days} day(s)",
  "daily.backfill.modal.existingNotes": "Existing Daily Notes in range: {count}",
  "daily.backfill.modal.invalid": "Start date must be on or before end date.",
  "daily.backfill.modal.body": "Missing notes are skipped. Existing managed content is preserved. Content outside the markers is never modified.",
  "daily.backfill.modal.confirm": "Backfill",
  "daily.backfill.modal.cancel": "Cancel",
  "daily.backfill.done": "Trakt Vault Sync: backfilled {wrote} day(s), skipped {skipped}.",
  "daily.catchUpDone.todayOnly": "Trakt Vault Sync: Daily Note updated.",
  "daily.catchUpDone.withPast": "Trakt Vault Sync: Daily Note updated, {wrote} past day(s) filled.",
  "daily.catchUpDone.pastOnly": "Trakt Vault Sync: {wrote} past day(s) filled.",
  "daily.today.updated": "Trakt Vault Sync: today's Daily Note updated.",
  "daily.today.noFile": "Trakt Vault Sync: no Daily Note for today.",
  "daily.today.unchanged": "Trakt Vault Sync: today's Daily Note is up to date.",
  "syncResult.dailyNotes.todayOnly": " Daily Note updated.",
  "syncResult.dailyNotes.withPast": " Daily Note updated; {wrote} past day(s) filled.",
  "syncResult.dailyNotes.pastOnly": " {wrote} past day(s) filled.",
  "daily.disabled": "Trakt Vault Sync: Daily Notes integration is disabled.",
  "cmd.syncDailyNotesToday": "Sync to Daily Notes",
  "plugin.version.name": "Version",
  "plugin.version.buildDate": "Build created: {date}",
  "plugin.version.openWhatsNew": "Open update notes",
  "auth.heading": "Authentication",
  "auth.clientId.name": "Trakt client ID",
  "auth.clientId.desc": "Create an app at trakt.tv/oauth/applications.",
  "auth.clientSecret.name": "Trakt client secret",
  "auth.clientSecret.desc": "From the same application page.",
  "auth.connection.name": "Connection status",
  "auth.connection.connected": "Connected to Trakt.",
  "auth.connection.notConnected": "Not connected.",
  "auth.connection.disconnect": "Disconnect",
  "auth.connection.connect": "Connect",
  "auth.connection.disconnectedNotice": "Trakt Vault Sync: disconnected.",
  "auth.connection.needCredentialsNotice": "Trakt Vault Sync: fill in client ID and secret first.",
  "auth.sync.name": "Cross-device sync",
  "auth.sync.desc": "Settings are stored in this vault's plugin data folder.",
  "tmdb.heading": "TMDB",
  "tmdb.apiKey.name": "API key",
  "tmdb.apiKey.desc": "Recommended for poster images and metadata.",
  "tmdb.apiKey.placeholder": "Paste your API key",
  "tmdb.apiKey.test.name": "Test API key",
  "tmdb.apiKey.test.desc": "Verify the key with TMDB.",
  "tmdb.apiKey.test.button": "Test",
  "tmdb.apiKey.test.testing": "Testing…",
  "tmdb.apiKey.test.ok": "✓ Connected — your TMDB key works.",
  "tmdb.apiKey.test.empty": "Enter a TMDB key first.",
  "tmdb.apiKey.test.unauthorized": "✗ Invalid key.",
  "tmdb.apiKey.test.network": "✗ Couldn't reach TMDB.",
  "tmdb.posterSize.name": "Poster size",
  "tmdb.posterSize.desc": "Image size for posters embedded in notes.",
  "tmdb.cache.ttl.name": "TMDB cache TTL",
  "tmdb.cache.ttl.desc": "How long cached TMDB metadata stays fresh.",
  "tmdb.cache.ttl.never": "Never expire",
  "tmdb.cache.ttl.7": "7 days",
  "tmdb.cache.ttl.30": "30 days",
  "tmdb.cache.ttl.90": "90 days (default)",
  "tmdb.cache.ttl.365": "365 days",
  "tmdb.cache.entries": "Currently cached: {count} entries",
  "tmdb.cache.clear.name": "Clear TMDB cache",
  "tmdb.cache.clear.desc": "Drop cached metadata so the next sync refetches it.",
  "tmdb.cache.clear.button": "Clear cache",
  "tmdb.cache.clear.notice": "Trakt Vault Sync: TMDB cache cleared.",
  "notes.heading": "Notes",
  "notes.folder.name": "Notes folder",
  "notes.folder.desc": "Vault folder where notes are stored.",
  "notes.filename.name": "Filename template",
  "notes.filename.desc": "Variables: {{title}}, {{year}}, {{imdb_id}}, {{trakt_id}}.",
  "notes.prefix.name": "Property prefix",
  "notes.prefix.desc": "Prefix for frontmatter properties.",
  "templates.heading": "Note templates",
  "templates.movie.name": "Movie note template",
  "templates.movie.desc": "Uses {{variable}} syntax.",
  "templates.show.name": "Show template",
  "templates.show.desc": "Uses {{variable}} syntax.",
  "templates.reset": "Reset to default",
  "tags.heading": "Tags",
  "tags.add.name": "Add tags",
  "tags.add.desc": "Add metadata tags to frontmatter.",
  "tags.prefix.name": "Tag prefix",
  "tags.prefix.desc": "Prefix for generated tags.",
  "tagNotes.heading": "Tag notes",
  "tagNotes.heading.desc": "Topic files linked from media notes.",
  "tagNotes.add.name": "Add tag notes to frontmatter",
  "tagNotes.add.desc": "Add tag-note wikilinks to frontmatter.",
  "tagNotes.create.name": "Create tag notes",
  "tagNotes.create.desc": "Create missing tag-note files.",
  "tagNotes.folder.name": "Tag notes folder",
  "tagNotes.folder.desc": "Folder for generated tag notes.",
  "syncSources.heading": "Sync sources",
  "syncSources.watchlist.name": "Sync watchlist",
  "syncSources.watchlist.desc": "Items you want to watch.",
  "syncSources.favorites.name": "Sync favorites",
  "syncSources.favorites.desc": "Items marked as favorites.",
  "syncSources.watched.name": "Sync watch history",
  "syncSources.watched.desc": "Items you've watched.",
  "syncSources.watchedDetail.name": "Detailed watch history",
  "syncSources.watchedDetail.desc": "Add per-episode or per-movie watch timestamps.",
  "history.fullRefreshInterval.name": "History full-refresh interval (days)",
  "history.fullRefreshInterval.desc": "How often to refetch complete history to detect deletions.",
  "history.state.stats": "Tracked: {movies} movies, {shows} shows, {events} watch events",
  "history.state.clear.name": "Clear history state",
  "history.state.clear.desc": "Rebuild detailed watch history on the next sync.",
  "history.state.clear.button": "Clear history state",
  "history.state.clear.notice": "Trakt Vault Sync: watch history cleared.",
  "syncSources.ratings.name": "Sync ratings",
  "syncSources.ratings.desc": "Items you've rated.",
  "syncBehavior.heading": "Sync behavior",
  "syncBehavior.movies.name": "Sync movies",
  "syncBehavior.movies.desc": "Include movies.",
  "syncBehavior.shows.name": "Sync shows",
  "syncBehavior.shows.desc": "Include shows.",
  "syncBehavior.startup.name": "Sync on startup",
  "syncBehavior.startup.desc": "Sync when Obsidian starts.",
  "syncBehavior.autoSync.name": "Auto-sync",
  "syncBehavior.autoSync.desc": "Sync periodically.",
  "syncBehavior.interval.name": "Auto-sync interval (minutes)",
  "syncBehavior.interval.desc": "Minimum 5, maximum 360.",
  "syncBehavior.communityStats.policy.name": "Community stats update policy",
  "syncBehavior.communityStats.policy.desc": "Control how often ratings and vote counts are written.",
  "syncBehavior.communityStats.policy.everySync": "Every sync",
  "syncBehavior.communityStats.policy.smart": "Smart",
  "syncBehavior.communityStats.interval.name": "Minimum update interval (days)",
  "syncBehavior.communityStats.interval.desc": "Minimum 1, maximum 30.",
  "syncBehavior.communityStats.ratingThreshold.name": "Rating change threshold",
  "syncBehavior.communityStats.ratingThreshold.desc": "Minimum rating change to write.",
  "syncBehavior.communityStats.votesThreshold.name": "Votes change threshold (%)",
  "syncBehavior.communityStats.votesThreshold.desc": "Minimum vote-count change to write.",
  "syncBehavior.overwrite.name": "Overwrite existing note body",
  "syncBehavior.overwrite.desc": "Regenerate the full note body on every sync.",
  "syncBehavior.delete.name": "Remove notes for deleted items",
  "syncBehavior.delete.desc": "Move removed items' notes to trash.",
  "syncMaintenance.heading": "Maintenance",
  "syncMaintenance.dedupe.name": "Deduplicate synced notes",
  "syncMaintenance.dedupe.desc": "Move duplicate synced notes to trash.",
  "syncMaintenance.dedupe.button": "Deduplicate",
  "syncMaintenance.dedupe.running": "Deduplicating…",
  "syncMaintenance.dedupe.done": "Trakt Vault Sync: scanned {groups} duplicate groups, trashed {trashed}, renamed {renamed}, failed {failed}.",
  "confirm.cancel": "Cancel",
  "confirm.disconnect.title": "Disconnect Trakt account?",
  "confirm.disconnect.body": "This removes saved Trakt tokens. Notes and settings remain.",
  "confirm.disconnect.confirm": "Disconnect",
  "confirm.clearTmdb.title": "Clear TMDB cache?",
  "confirm.clearTmdb.body": "This clears cached TMDB metadata. Notes are unchanged until the next sync.",
  "confirm.clearTmdb.confirm": "Clear cache",
  "confirm.clearHistory.title": "Clear watch-history state?",
  "confirm.clearHistory.body": "The next detailed sync will rebuild watch history.",
  "confirm.clearHistory.confirm": "Clear history state",
  "confirm.dedupe.title": "Deduplicate synced notes?",
  "confirm.dedupe.body": "Duplicate notes will be moved to trash.",
  "confirm.dedupe.confirm": "Deduplicate",
  "confirm.reset.title": "Reset settings to defaults?",
  "confirm.reset.body": "Authentication is preserved. Existing notes are unchanged.",
  "confirm.reset.confirm": "Reset settings",
  "reset.heading": "Reset",
  "reset.button.name": "Reset to defaults",
  "reset.button.desc": "Reset settings while preserving authentication.",
  "reset.notice": "Trakt Vault Sync: settings reset to defaults.",
  "cmd.sync": "Sync",
  "cmd.connect": "Connect account",
  "cmd.disconnect": "Disconnect account",
  "cmd.forceFullHistoryRefresh": "Force full watch-history refresh",
  "cmd.clearTmdbCache": "Clear TMDB metadata cache",
  "notice.notConnected": "Trakt Vault Sync: not connected.",
  "notice.needCredentials": "Trakt Vault Sync: fill in client ID and secret first.",
  "notice.alreadySyncing": "Trakt Vault Sync: sync already running.",
  "notice.migratedFromLegacyFolder": "Trakt Vault Sync: settings migrated from the legacy plugin folder.",
  "settings.cloud.synced.tooltip": "Synced across devices. Click to make device-local.",
  "settings.cloud.local.tooltip": "Local to this device. Click to sync.",
  "notice.syncComplete": "Trakt Vault Sync: {added} new, {updated} updated, {unchanged} unchanged, {removed} removed.",
  "notice.syncCompleteWithFailures": " {failed} failed.",
  "notice.syncCompleteWithRenames": " {renamed} renamed.",
  "notice.syncFailed": "Trakt Vault Sync: sync failed — {msg}",
  "notice.syncMore": " (+{count} more — see console)",
  "status.syncing": "⟳ Syncing…",
  "status.dailySyncing": "⟳ Syncing Daily Notes…",
  "status.prefix": "Trakt Vault Sync: ",
  "progress.fetchingTrakt": "⟳ Fetching from Trakt…",
  "progress.fetchingTraktHistory": "⟳ Fetching new watch events…",
  "progress.fullHistoryRefresh": "⟳ Full history refresh…",
  "progress.fetchingMetadata": "⟳ Loading metadata: {done}/{total}",
  "progress.fetchingTranslations": "⟳ Loading metadata: {done}/{total}",
  "progress.writingNotes": "⟳ Writing notes: {done}/{total}",
  "authModal.title": "Connect",
  "authModal.requestingCode": "Requesting device code...",
  "authModal.openLink": "Open the link below and enter the code:",
  "authModal.copyHint": "Click to copy",
  "authModal.codeCopied": "Trakt Vault Sync: pairing code copied.",
  "authModal.codeExpiresIn": "Code expires in {n}s",
  "authModal.codeExpired": "Code expired. Please close and try again.",
  "authModal.cancel": "Cancel",
  "authModal.success": "Trakt Vault Sync: connected to Trakt.",
  "authModal.errorPrefix": "Error: {msg}",
  "authModal.failedStart": "Failed to start auth: {msg}",
  "auth.error.notConnected": "Not connected to Trakt.",
  "auth.error.sessionExpired": "Trakt session expired. Please reconnect.",
} as const;

export type StringKey = keyof typeof STRINGS;
export type UiLanguage = "en";

export function t(
  key: StringKey,
  _language: UiLanguage = "en",
  vars?: Record<string, string | number>,
): string {
  let value: string = STRINGS[key];
  for (const [name, replacement] of Object.entries(vars ?? {})) {
    value = value.split(`{${name}}`).join(String(replacement));
  }
  return value;
}

export function getTranslator(_language: UiLanguage = "en") {
  return (key: StringKey, vars?: Record<string, string | number>) =>
    t(key, "en", vars);
}
